title: Wanglab's Homepage
page-top-title: Xiaohong Wang
top-section-bg-text: Laboratory of Molecular Ophthalmology 
home-subtitle: Xiaohong Wang&ensp;|&ensp;王晓虹
copyright-text: '&copy; TIANJIN MEDICAL UNIVERSITY. No. 22. QIXIANGTAI ROAD, TIANJIN, CHINA, 300070 .'
